version: '3.8'

services:

  # frontend:
  #   build: ./Frontend
  #   container_name: frontend
  #   command: sh -c "npm run build"
  #   volumes:
  #     - frontend-dist:/app/dist
  #   networks:
  #     - app-network

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - frontend-dist:/usr/share/nginx/html
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - app-network

  # backend:
  #   build: ./Backend
  #   container_name: backend
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./Backend/.env
  #   depends_on:
  #     - mysql
  #     - redis
  #   networks:
  #     - app-network

  flask:
    build: ./AI_Service
    ports:
      - "5000:5000"
    env_file:
      - ./AI_Service/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  # mysql:
  #   image: mysql:8
  #   container_name: dbmysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Minecraft24_01
  #     MYSQL_DATABASE: finance_ai
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - app-network
  
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379"
  #   networks:
  #     - app-network

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network


volumes:
  # mysql-data:
  mongo_data:
  # frontend-dist:

networks:
  app-network:
    driver: bridge